# Generated by Django 4.2.16 on 2024-09-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFactTask',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in progress', 'In Progress')], default='in progress', max_length=20)),
                ('started', models.DateTimeField()),
                ('completed', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.task')),
            ],
        ),
    ]
