# Generated by Django 4.2.16 on 2024-09-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catfactsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catfacttask',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
