# Generated by Django 4.2.16 on 2024-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catfactsapp', '0003_alter_catfacttask_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catfacttask',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('In Progress', 'In Progress')], default='In Progress', max_length=20),
        ),
    ]
